### ISSUE TITLE
setup.py does not build/install HTML template files from plugin subdirectories

### ISSUE THREAD

**Issue by dhmint** [ocdude/mbzextract#7]
Python setuptools.find_packages looks for Python modules only, not including template folders in the package list. This can be fixed by adding the option `include_package_data=True` to the setup() call in setup.py and by creating a file MANIFEST.in in the project directory containing the lines
`include mbzextract/plugins/page/templates/*`
`include mbzextract/plugins/assignment/templates/*`

**Comment by ocdude** [comment]
Thanks for the report. Updated.
